<a href="https://colab.research.google.com/github/tymkasz/deep-learning-with-john-elder/blob/main/tensors_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(18)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [9]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])

In [11]:
my_torch2 = my_torch2.reshape(-1,6)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])

In [12]:
# View
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

[Differences between reshape() and view()](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch?rq=1)

In [14]:
# With reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch5[1] = 4232
my_torch5

tensor([   0, 4232,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
# Making changes to the original tensor, changes will be reflected
my_torch6

tensor([[   0, 4232,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [19]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# It is different than regular 7, it is kinda like scalar -> grab a specific item
my_torch7[7]

tensor(7)

In [21]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
# return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])