<a href="https://colab.research.google.com/github/tymkasz/deep-learning-with-john-elder/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**
*   Add, substract, multiply, divide, remainders, exponents, modules
*   Shorthand and Longhand
*   Reassignment

In [23]:
import torch
import numpy as np

In [24]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [25]:
# Same amount of elements
# Add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# Substract
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [28]:
# Sub Function
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [29]:
# Multiply
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [30]:
# Mul Function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [31]:
# Divide
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [32]:
# Div Longhand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [33]:
# Remainder Modulus
tensor_b % tensor_a
## Divided by corresponding element

tensor([0, 0, 1, 0])

In [34]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [35]:
# Exponent (power)
tensor_a ** tensor_b
## Power of coressponding element

tensor([    1,    64,  2187, 65536])

In [36]:
# Power longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [37]:
# Another way to write longhand
tensor_a.add(tensor_b)
tensor_a.sub(tensor_b)
tensor_a.mul(tensor_b)
tensor_a.div(tensor_b)
tensor_a.remainder(tensor_b)
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [38]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [39]:
# tensor_a = tensor_a + tensor_b - the same as below -> _
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

In [39]:
# torch.add_(tensor_a, tensor_b) - wrong!