<a href="https://colab.research.google.com/github/tymkasz/deep-learning-with-john-elder/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**



*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type
*   Similar to numpy arrays, but better on GPU's
*   default data type of float32
*   More suitable for deep learning than a numpy array

In [1]:
import torch
import numpy as np

## **LISTS**

In [3]:
list = [[1,2,3,4,5], [6,7,8,9,10]]
list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## **NUMPY ARRAYS**

In [4]:
np_array = np.random.rand(3,4)
np_array

array([[0.96455794, 0.69045027, 0.20997343, 0.37459306],
       [0.59387429, 0.38690267, 0.61347481, 0.59432595],
       [0.03443538, 0.27842486, 0.12599911, 0.45022161]])

In [5]:
np_array.dtype

dtype('float64')

## **TENSORS**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8603,  0.9088,  0.6338, -0.6193],
        [-1.6337,  1.0062, -0.2753, -1.0798],
        [ 0.3669,  1.3353, -0.0077,  1.3840]])

In [14]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.9695, -0.2936, -0.0594, -0.1692],
         [-1.0895, -1.2213,  0.6265,  0.8315],
         [-0.4352, -1.7849,  1.7359,  1.9785]],

        [[-0.6365,  0.8686,  0.8337, -0.0800],
         [ 1.6913,  1.5148, -1.0639, -1.7780],
         [ 1.0115,  1.5302, -1.9982, -0.9715]]])

In [13]:
tensor_3d.dtype

torch.float32

In [9]:
tensor_3d_zeros = torch.zeros(2,3,4)
tensor_3d_zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np_array)
my_tensor

tensor([[0.9646, 0.6905, 0.2100, 0.3746],
        [0.5939, 0.3869, 0.6135, 0.5943],
        [0.0344, 0.2784, 0.1260, 0.4502]], dtype=torch.float64)

In [18]:
## Reshaping tensors
reshaped_tensor = my_tensor.reshape(4,3)
reshaped_tensor

tensor([[0.9646, 0.6905, 0.2100],
        [0.3746, 0.5939, 0.3869],
        [0.6135, 0.5943, 0.0344],
        [0.2784, 0.1260, 0.4502]], dtype=torch.float64)